[versions]
agp = "8.2.1"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-lib = { id = "com.android.library", version.ref = "agp" }
lsplugin-jgit = { id = "org.lsposed.lsplugin.jgit", version = "1.1" }
lsplugin-publish = { id = "org.lsposed.lsplugin.publish", version = "1.1" }
lsplugin-cmaker = { id = "org.lsposed.lsplugin.cmaker", version = "1.2" }

[libraries]
cxx = { module = "dev.rikka.ndk.thirdparty:cxx", version = "1.2.0" }
dobby = { module = "io.github.vvb2060.ndk:dobby", version = "1.2" }
test-ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
test-runner = { module = "androidx.test:runner", version = "1.5.2" }
test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }

